#!/usr/bin/env python3
"""Generate documentation pages from source code.

Run before mkdocs build to keep auto-generated pages in sync:

    python docs/generate.py

Generates:
- docs/reference/cli.md              — CLI reference from typer introspection
- docs/_generated/formats-table.md   — supported formats table from handler registry
- docs/_generated/rai-flags-table.md — RAI CLI flags table from typer app
"""

import inspect
import os
import subprocess
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).parent
GENERATED_DIR = DOCS_DIR / "_generated"
PROJECT_ROOT = DOCS_DIR.parent
SRC_DIR = str(PROJECT_ROOT / "src")


def generate_cli_reference() -> None:
    """Generate CLI reference from the typer app."""
    cli_path = DOCS_DIR / "reference" / "cli.md"
    env = os.environ.copy()
    env["PYTHONPATH"] = SRC_DIR + os.pathsep + env.get("PYTHONPATH", "")
    subprocess.run(
        [
            sys.executable,
            "-m",
            "typer",
            str(PROJECT_ROOT / "src" / "croissant_baker" / "__main__.py"),
            "utils",
            "docs",
            "--output",
            str(cli_path),
        ],
        check=True,
        env=env,
    )
    # Prepend auto-generated comment
    content = cli_path.read_text()
    cli_path.write_text(
        "<!-- Auto-generated by docs/generate.py — do not edit manually -->\n\n"
        + content
    )
    print("Generated docs/reference/cli.md")


def generate_formats_table() -> None:
    """Generate the supported formats table from the handler registry."""
    sys.path.insert(0, SRC_DIR)
    from croissant_baker.compression import compressions
    from croissant_baker.handlers.base_handler import InputKind
    from croissant_baker.handlers.registry import (
        get_registered_handlers,
        register_all_handlers,
    )

    register_all_handlers()
    handlers = get_registered_handlers()
    wrappers = ", ".join(f"`{c.suffix}`" for c in compressions())

    lines = [
        "<!-- Auto-generated by docs/generate.py — do not edit manually -->",
        "",
        "| Format | Extensions | Compression | What's extracted |",
        "|--------|-----------|-------------|-----------------|",
    ]
    for handler in handlers:
        exts = ", ".join(f"`{e}`" for e in handler.EXTENSIONS)
        comps = wrappers if handler.INPUT_KIND is InputKind.STREAM else "—"
        lines.append(
            f"| {handler.FORMAT_NAME} | {exts} | {comps} | {handler.FORMAT_DESCRIPTION} |"
        )

    GENERATED_DIR.mkdir(exist_ok=True)
    (GENERATED_DIR / "formats-table.md").write_text("\n".join(lines) + "\n")
    print("Generated docs/_generated/formats-table.md")


def generate_rai_flags_table() -> None:
    """Generate the RAI CLI flags table from typer parameter inspection."""
    sys.path.insert(0, SRC_DIR)
    from croissant_baker.__main__ import main

    lines = [
        "<!-- Auto-generated by docs/generate.py — do not edit manually -->",
        "",
        "| Flag | Description |",
        "|------|-------------|",
    ]

    sig = inspect.signature(main)
    for name, param in sig.parameters.items():
        if not name.startswith("rai_") or name == "rai_config":
            continue
        default = param.default
        if hasattr(default, "help"):
            flag = "--" + name.replace("_", "-")
            help_text = default.help or ""
            lines.append(f"| `{flag}` | {help_text} |")

    GENERATED_DIR.mkdir(exist_ok=True)
    (GENERATED_DIR / "rai-flags-table.md").write_text("\n".join(lines) + "\n")
    print("Generated docs/_generated/rai-flags-table.md")


if __name__ == "__main__":
    generate_cli_reference()
    generate_formats_table()
    generate_rai_flags_table()
    print("Done.")
